### ISSUE TITLE
IndexError on Strings containing Certain Characters

### ISSUE THREAD

**Issue by matt-buckley** [egerber/spaCy-entity-linker#10]
When running a basic NLP model like en_core_web_lg with the sole addition of an entityLinker pipe, calling nlp() will throw an IndexError on certain strings, particularly those with certain whitespace characters such as newline characters. The error thrown and the line causing the error is:

`def _get_candidates_in_sent(self, sent, doc):
  ---->   root = list(filter(lambda token: token.dep_ == "ROOT", sent))[0]
              excluded_children = []
              candidates = []

IndexError: list index out of range`

I'm running Python version 3.9, spaCy version 3.2.4, and spaCy-entity-linker version 1.0.1

**Comment by ninikolov** [comment]
Same here

**Comment by isu-shrestha** [comment]
Having the same problem here. 
Did a temporary fix by removing white space:
text = ' '.join(text.split())

**Comment by MartinoMensio** [comment]
Hi @matt-buckley @ninikolov and @isu-shrestha ,
Thank you for opening the issue. I recently became a maintainer of this package and did not notice the open issue.
I just tested and merged #9 which should fix the issue. Can you confirm on your end?

Best,
Martino

**Comment by dennlinger** [comment]
Hi @MartinoMensio,
I also encountered this issue not too long ago (tried it two weeks ago and it failed). For my particular file, it now works! Thanks @jonwiggins  for the fix :partying_face:

I'll contribute a PR with an additional test case, containing a minimal document sample that caused a crash. This way future iterations have a better checking and you can reproduce the issue yourself.

**Comment by MartinoMensio** [comment]
Hi @dennlinger,
Thank you very much for joining this issue and for confirming that now it works!
I'm looking forward to receiving your PR with the test case! This project needs it :)

Best,
Martino
