### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by k-gruenberg** [egerber/spaCy-entity-linker#11]
Trying to download the knowledge base from `https://wikidatafiles.nyc3.digitaloceanspaces.com/Hosting/Hosting/SpacyEntityLinker/datafiles.tar.gz` fails with a `403: Forbidden` error.

**Comment by jayhpatel14** [comment]
I also have the same issue

**Comment by MartinoMensio** [comment]
Hi everyone,
I still had a local copy of the knowledge base, and I uploaded it here: https://huggingface.co/MartinoMensio/spaCy-entity-linker/resolve/main/knowledge_base.tar.gz

I hope you can find this useful. I sent a PR to update the links.

Best,
Martino

**Comment by MartinoMensio** [comment]
Hi @k-gruenberg and @jayhpatel14 ,
The new version 1.0.2 fixes this issue. Please update it from pypi.

Best,
Martino

**Comment by oldmonkABA** [comment]
Hi @MartinoMensio I am getting the following error : 
sqlite3.OperationalError: no such table: statements
